import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Demo App",
  description: "Generated by create next Demo operation",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`body`}
      >
        {children}
      </body>
    </html>
  );
}
