import Link from "next/link";
import "./globals.css";
export const metadata = {
    title: "Next js Rock app",
    description: "Generated by Next js and organize by SAYED",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`body`}>
                <nav className="container mx-auto mb-5 bg-cyan-200 p-3">
                    <ul className="m-0 flex gap-x-4 p-0">
                        <li>
                            <Link href="/">Home</Link>
                        </li>
                        <li>
                            <Link href={"/about"}>About</Link>
                        </li>
                        <li>
                            <Link href={"/posts"}>Blog posts</Link>
                        </li>
                    </ul>
                </nav>
                <div className="container mx-auto">{children}</div>
            </body>
        </html>
    );
}
